
version: 0.2

Phrases:
  install:
    commands:
      - echo 'Installing dotNet 6'
      - /usr/local/bin/dotnet-install.sh --channel LTS

  pre_build:
    commands:
      - echo 'Restoring dependencies of each prodject (the packages) and unit testing'
      - dotnet restore


  build:
    commands:
      - echo 'Building the app'
      - dotnet build

  post_build:
    commands:
      - echo 'Creating the publish folder for the app'
      - dotnet publish -c Release -o publish

artifacts:
  files:
    - 'Dockerfile'
    - 'publish/**/*'

